In [122]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [97]:
df = pd.read_csv("D:\CDAC\Machine Learning\Module_Exam\sales.csv")

In [98]:
df.shape

(14, 6)

In [99]:
df.head(14)

ID    Age  Income  Gender Marital Status Buys
0    1    <21    High    Male         Single   No
1    2    <21    High    Male        Married   No
2    3  21-35    High    Male         Single  Yes
3    4    >35  Medium    Male         Single  Yes
4    5    >35     Low  Female         Single  Yes
5    6    >35     Low  Female        Married   No
6    7  21-35     Low  Female        Married  Yes
7    8    <21  Medium    Male         Single   No
8    9    <21     Low  Female        Married  Yes
9   10    >35  Medium  Female         Single  Yes
10  11    <21  Medium  Female        Married  Yes
11  12  21-35  Medium    Male        Married  Yes
12  13  21-35    High  Female         Single  Yes
13  14    >35  Medium    Male        Married   No

In [100]:
df.describe

<bound method NDFrame.describe of     ID    Age  Income  Gender Marital Status Buys
0    1    <21    High    Male         Single   No
1    2    <21    High    Male        Married   No
2    3  21-35    High    Male         Single  Yes
3    4    >35  Medium    Male         Single  Yes
4    5    >35     Low  Female         Single  Yes
5    6    >35     Low  Female        Married   No
6    7  21-35     Low  Female        Married  Yes
7    8    <21  Medium    Male         Single   No
8    9    <21     Low  Female        Married  Yes
9   10    >35  Medium  Female         Single  Yes
10  11    <21  Medium  Female        Married  Yes
11  12  21-35  Medium    Male        Married  Yes
12  13  21-35    High  Female         Single  Yes
13  14    >35  Medium    Male        Married   No>

In [101]:
df["Buys"].value_counts()

Yes    9
No     5
Name: Buys, dtype: int64

In [102]:
df.head()

ID    Age  Income  Gender Marital Status Buys
0   1    <21    High    Male         Single   No
1   2    <21    High    Male        Married   No
2   3  21-35    High    Male         Single  Yes
3   4    >35  Medium    Male         Single  Yes
4   5    >35     Low  Female         Single  Yes

In [103]:
# Preprocessing

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df = df.apply(le.fit_transform)

In [104]:
df

ID  Age  Income  Gender  Marital Status  Buys
0    0    1       0       1               1     0
1    1    1       0       1               0     0
2    2    0       0       1               1     1
3    3    2       2       1               1     1
4    4    2       1       0               1     1
5    5    2       1       0               0     0
6    6    0       1       0               0     1
7    7    1       2       1               1     0
8    8    1       1       0               0     1
9    9    2       2       0               1     1
10  10    1       2       0               0     1
11  11    0       2       1               0     1
12  12    0       0       0               1     1
13  13    2       2       1               0     0

In [105]:
df = df.drop(['ID'],axis =1)

In [106]:
df.head()

Age  Income  Gender  Marital Status  Buys
0    1       0       1               1     0
1    1       0       1               0     0
2    0       0       1               1     1
3    2       2       1               1     1
4    2       1       0               1     1

In [107]:
#Independent and Dependent variables
X = df.iloc[:,:-1].values

y = df.iloc[:,-1].values

In [108]:
X

array([[1, 0, 1, 1],
       [1, 0, 1, 0],
       [0, 0, 1, 1],
       [2, 2, 1, 1],
       [2, 1, 0, 1],
       [2, 1, 0, 0],
       [0, 1, 0, 0],
       [1, 2, 1, 1],
       [1, 1, 0, 0],
       [2, 2, 0, 1],
       [1, 2, 0, 0],
       [0, 2, 1, 0],
       [0, 0, 0, 1],
       [2, 2, 1, 0]])

In [109]:
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [110]:
#Train and Test Data

from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,train_size=0.33,random_state=0)

In [118]:
X_train.shape , X_test.shape , y_train.shape , y_test.shape

((4, 4), (10, 4), (4,), (10,))

In [111]:
#Model Building

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy' , random_state=0)
classifier.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [112]:
y_pred = classifier.predict(X_test)

In [113]:
y_pred

array([0, 1, 0, 1, 1, 1, 1, 0, 1, 1])

In [114]:
from sklearn.metrics import confusion_matrix , accuracy_score , classification_report

#Confusion Matrix
cm = confusion_matrix(y_test , y_pred)
cm

array([[1, 2],
       [2, 5]], dtype=int64)

In [115]:
#Accuracy Score
accuracy_score(y_test , y_pred)

0.6

In [120]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.33      0.33      0.33         3
           1       0.71      0.71      0.71         7

    accuracy                           0.60        10
   macro avg       0.52      0.52      0.52        10
weighted avg       0.60      0.60      0.60        10



In [116]:
classifier.predict([[0,0,1,1]])

array([1])

In [117]:
classifier.predict([[1,1,0,0]])

array([0])

## Conclusion

Root Node for the decision tree is 'Age'

Predicted class for input [Age>21 , Income = Low , Gender = Female , Marital Status = Married]
i. e. [1,1,0,0] is No[0]

So , The accuracy for this model is 60%.